### PR TITLE
Restructure the folder organization, python3 compatible, sededu compatible

### PR DESCRIPTION
**Pull request by amoodie**
@jeffskwang,

This PR represents changes only to the organization and compatibility of the codebase; there are no functional changes. You can see all the changes outlined below.

I have:
* moved the source code to a folder called `src`.
* added a file in the main repo folder called `run_rain_table.py` that is basically just a simple wrapper pointing to the source code. It takes (optionally) one argument to be able to run in Python 3.
* moved the data and images into a folder called `private` and updated the source code to point to these folders.
* added a file called `about.json` that provides some information about the module, this allows it to work with SedEdu.
* changed your use of `xrange` which doesn't exist in Python to `numpy`'s `arange`, so that it will run with both platforms.

### CODE REVIEW

**Comment by amoodie** [comment]
@jeffskwang great, thanks for merging!

Just to be sure, you'll need to get this version down to your machine before you do any more development, so that we are working from a common base. 
```
git pull origin master
```
should do it for you. 

Cheers, AM

**Comment by amoodie** [comment]
@jeffskwang also, would probably be good to test it out in your environment to make sure I didn't break anything (you can "revert" above if needed) and I'll fix it. 

I tested on my Python 2.7 installation, but just to be sure you'd better check too.

**Comment by jeffskwang** [comment]
I just put it on my machine. If I run the file in the src folder, it works
perfectly.

Should I be able to run the code form the run_rain_table.py file? I'm not
exactly sure what sys.argv does.

I get this error:

  File "C:\Users\jeffs\Documents\GitHub\rain_table\run_rain_table.py", line
9, in <module>
    if sys.argv[1] == '--python3':
IndexError: list index out of range

**Comment by amoodie** [comment]
Ah shoot yeah, it's because there is always one argument passed, I need to threshold at `>1` not `>0`.

In `run_rain_table.py` can you change 
```
if len(sys.argv) > 0:
```
to
```
if len(sys.argv) > 1:
```

and try? I'll fix and push if that works. Or you can?

**Comment by jeffskwang** [comment]
I don't think it works for me; I don't get an error, but it doesn't enter
the if statement to run the code. Maybe something like this will fix it?

# if commands given
if len(sys.argv) > 1:
    # argument for python 3 runtime
    if sys.argv[1] == '--python3':
        os.system('python3 ' + os.path.join(this_dir, 'src',
'rain_table.py'))
else: #remove this tab?
    os.system('python ' + os.path.join(this_dir, 'src', 'rain_table.py'))

**Comment by amoodie** [comment]
Duh. Yeah, that's totally how I wrote it in my head, but obviously it came out a little different. Better add a second run command though for if unknown argument is given.

```
# if commands given
if len(sys.argv) > 1:
    # argument for python 3 runtime
    if sys.argv[1] == '--python3':
        os.system('python3 ' + os.path.join(this_dir, 'src', 'rain_table.py'))
    else:
        os.system('python ' + os.path.join(this_dir, 'src', 'rain_table.py'))
else: 
    os.system('python ' + os.path.join(this_dir, 'src', 'rain_table.py'))
```
Does this change fix the issue?

**Comment by jeffskwang** [comment]
Works for me.  I'll merge it now. Thanks,

Jeffrey

**Comment by amoodie** [comment]
great, sorry about the trouble. Should have tested the code some more 

Also, if you're looking to use GitHub more (I recommend it, open and collaborative science!) then you may find these resources helpful; they really helped me start to figure out the workflow, which to be sure, I am still figuring out too.

https://guides.github.com/features/mastering-markdown/
https://git-scm.com/book/pl/v2/GitHub-Contributing-to-a-Project

**Comment by jeffskwang** [comment]
Thanks for the links and help. Jeffrey

**Pull request merged**
